### PR TITLE
Upgrade to Eclipse Mars and jshint 2.9.0

### PR DESCRIPTION
**Pull request by thallgren**
This commit changes the repository configuration to use the Eclipse
Mars release, the latest Orbit repository and the latest release
of swtbot. It also changes the current jshint release to 2.9.0 and
adds compatibility tests for 2.6.3, 2.7.0, 2.8.0, and 2.9.0.

The commit also changes the release from 0.9.11 to 0.10.0.

### CODE REVIEW

**Comment by thallgren** [comment]
This commit will also close #102.

**Comment by paulvi** [comment]
Hooray! :+1:

**Comment by ralfstx** [comment]
Great, thank you!

**Comment by ralfstx** [comment]
I've updated the update site to include 0.10.0.

**Comment by thallgren** [comment]
That was quick. Thanks!

**Pull request merged**
